// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDprLjyQHgnIbOpVHKXxP1-UCCwG9GsI',
    appId: '1:287447492369:web:a04f714bf3f9fc8c490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    authDomain: 'projetomobile-35311.firebaseapp.com',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_PnvQdwPrElfmWMD5Gsr-ZfjmBH3WTEc',
    appId: '1:287447492369:android:d7d16defe082451b490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOduRgncisHXWa0SHNvamXcwvgiBBk6l0',
    appId: '1:287447492369:ios:f26223ee6375166d490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
    iosBundleId: 'com.example.sportscbr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOduRgncisHXWa0SHNvamXcwvgiBBk6l0',
    appId: '1:287447492369:ios:f26223ee6375166d490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
    iosBundleId: 'com.example.sportscbr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyDprLjyQHgnIbOpVHKXxP1-UCCwG9GsI',
    appId: '1:287447492369:web:21f5a8b59e387de1490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    authDomain: 'projetomobile-35311.firebaseapp.com',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
  );

}